version: '3.5'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: udb
      POSTGRES_USER: u
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: test_task
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/udb
      SPRING_DATASOURCE_USERNAME: u
      SPRING_DATASOURCE_PASSWORD: 1