spring:
  profiles:
    active: test
---

spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://localhost:5433/udb
    username: u
    password: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: udb
